# Generated by Django 2.2.6 on 2019-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=50)),
                ('news_text', models.TextField()),
                ('news_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_name', models.CharField(max_length=50)),
                ('suggestion_text', models.TextField()),
                ('suggestion_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
